### ISSUE TITLE
can't install this module ix_sale_promotion on odoo v8

### ISSUE THREAD

**Issue by jaronemo** [afwanwh/ix_odoo_addons#3]
File "/opt/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
invalid syntax
('<string>', 1, 45, "{'invisible': [('type', 'not in', ('points')]}")" while parsing /opt/odoo/myaddons/ix_sale_promotion/sale_view.xml:16, near
<record id="form_view_sales_promotion_ix" model="ir.ui.view">
            <field name="name">form_view_sales_promotion_ix</field>
            <field name="model">sale.promotion</field>
            <field name="arch" type="xml">
                <form string="Sales Promotions" version="7.0">
                    <header>
                        <button name="turn_promotion_on" string="Turn ON" type="object" attrs="{'invisible': [('state','in',('on'))]}" class="oe_highlight"/>
                        <button name="turn_promotion_off" string="Turn OFF" type="object" attrs="{'invisible': [('state','in',('off'))]}" class="oe_highlight"/>
                        <field name="state" widget="statusbar" statusbar_visible="on, off"/>
                    </header>
                    <label for="name" class="oe_edit_only"/>
                    <h1><field name="name"/></h1>
                    <group>
                        <field name="code"/>
                        <field name="type"/>
                    </group>
                    <separator string="Promotion Rule" attrs="{'invisible': [('type','=',False)]}"/>
                    <group>
                        <group>
                            <field name="buy_qty" attrs="{'invisible': [('type','not in',('free'))]}"/>
                            <field name="amount_discount" attrs="{'invisible': [('type','not in',('fixed'))]}"/>
                            <field name="point_values" attrs="{'invisible': [('type','not in',('points'))]}"/>
                            <field name="points_categ" attrs="{'invisible': [('type', 'not in', ('points')]}"/>
                            <label for="percentage_discount" attrs="{'invisible': [('type','not in',('percentage'))]}"/>
                            <div attrs="{'invisible': [('type','not in',('percentage'))]}">
                                <field name="percentage_discount" class="oe_inline"/> percent
                            </div>
                        </group>
                        <group>
                            <field name="free_qty" attrs="{'invisible': [('type','not in',('free'))]}"/>
                            <field name="usage" attrs="{'invisible': [('type','not in',('fixed', 'percentage'))]}"/>
                        </group>
                    </group>
                </form>
           </field>
        </record>

**Comment by afwanwh** [comment]
This module is under development. It's not ready yet.
